### ISSUE TITLE
echarts导入问题

### ISSUE THREAD

**Issue by shopingxie** [sakitam-fdd/ol3Echarts#100]
- **环境**

    "echarts": "^4.6.0",
    "ol": "^5.3.3",
    "vue": "^3.2.25",
    "vue-router": "^4.0.14",
    "vuex": "^4.0.2",
打包工具
    "vite": "^2.8.0",

- **问题**

![QKV(4G$8)%XG K(TDI5VRP](https://user-images.githubusercontent.com/35999489/163078553-5d5d9dd8-d30f-44c9-a154-e652aba915de.png)

**Comment by sakitam-fdd** [comment]
没支持 vite，下个版本兼容一下

**Comment by sakitam-fdd** [comment]
@shopingxie https://codesandbox.io/s/sweet-hellman-0givkj
