### ISSUE TITLE
请教~ new EChartsLayer 报错怎么回事

### ISSUE THREAD

**Issue by wangbingbingaaa** [sakitam-fdd/ol3Echarts#115]
![image](https://user-images.githubusercontent.com/35550862/233253774-db0bd466-4a7e-4786-a7e0-d2936f479136.png)
![image](https://user-images.githubusercontent.com/35550862/233253892-2109cbf0-4cbc-4343-85f3-c73838f32708.png)
![image](https://user-images.githubusercontent.com/35550862/233253926-652bf51d-5927-4c69-bbcb-f73152d2a265.png)

 "ol": "^7.3.0",
 "ol-echarts": "^3.0.0",
"react-dom": "^18.2.0",
  "echarts": "^5.4.2",

**Comment by rolitter** [comment]
你好,最后你是怎么解决的?

**Comment by ComingB** [comment]
我是把ol版本降到"ol": "^6.9.0",解决的，你们可以试试

**Comment by hy31337** [comment]
同问，请问什么时候能否支持 "ol": "^7.3.0",

**Comment by sakitam-fdd** [comment]
@hy31337 晚点吧，目前还没计划，因为 ol 好久没用了，还得去研究源码。或者咱们有时间可以来个 PR 😄

**Comment by zapzqc** [comment]
这是由于将[Class转为ES5](https://stackoverflow.com/questions/51860043/)导致的。

已提交PR #116

**Comment by sakitam-fdd** [comment]
@zapzqc @hy31337 @rolitter @wangbingbingaaa 感谢 @zapzqc 的 PR，这个问题我追踪了一下，主要是由于 ol 版本从 6 开始完全转为了 class 语法（编译后的），详见 [V7](https://unpkg.com/browse/ol@7.4.0/Object.js) 和 [V6](https://unpkg.com/browse/ol@6.15.1/Object.js)，如果要修改的话可能需要做大版本升级

**Comment by sakitam-fdd** [comment]
示例：
vite：https://stackblitz.com/edit/vitejs-vite-feba7b
cra：https://stackblitz.com/edit/stackblitz-starters-t3hgqz
