### ISSUE TITLE
ol8+ol-echarts4无法显示热力图，有大佬帮忙看下么🤗

### ISSUE THREAD

**Issue by ytsxstone** [sakitam-fdd/ol3Echarts#119]
测试了ol5+ol-echarts@2.0.4可以显示热力图，升echarts5后无法显示热力图

**Comment by ytsxstone** [comment]
测试了ol5+ol-echarts@2.0.4可以显示热力图，升echarts5后无法显示热力图

**Comment by luoxiao-supermap** [comment]
ol@7.5.2 + ol-echarts@4.0.0 + echarts@5.5.0 热力图也不出图， 无报错

**Comment by xilanhuaweidapao** [comment]
因为在升级了ol5之后，RegisterCoordinateSystem 类新增了 setViewRect 方法，getViewRect 把设置 rect 的逻辑放到了 setViewRect 但是热力图并没有在 echarts 调用 set 方法导致没有设置，提了个pr来修复这种情况 [pr](https://github.com/sakitam-fdd/ol3Echarts/pull/123)
