### ISSUE TITLE
ol@7.5.2 使用ol-echarts@4 报错 Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by luoxiao-supermap** [sakitam-fdd/ol3Echarts#120]
ol@7.5.2 使用ol-echarts@4 报错
Cannot read properties of undefined (reading 'split')
ol@7.5.2的VERSION   是挂在    ol.util.VERSION
![image](https://github.com/sakitam-fdd/ol3Echarts/assets/97505033/696ef602-2de3-4357-bb73-2d1715c5e89e)

**Comment by sakitam-fdd** [comment]
@luoxiao-supermap 感谢，看到了你的 PR，但是有个问题：
我看从 7.5.2 版本一直到 9.x, VERSION 字段在主文件都有导出 https://github.com/openlayers/openlayers/blob/v7.5.2/src/ol/index.js

**Comment by luoxiao-supermap** [comment]
打包可能也有问题吧， external里面 ‘ol’ ： ‘ol’  ； 没有 'ol/util':  'ol.util'

**Comment by sakitam-fdd** [comment]
> 打包可能也有问题吧， external里面 ‘ol’ ： ‘ol’ ； 没有 'ol/util': 'ol.util'

倒不是导出的问题，就是默认从 5.0 版本起，所有的 VERSION 字段都是可以从 ol 直接导出的 https://github.com/openlayers/openlayers/blob/v7.5.2/src/ol/index.js 你那边能否提供最小可复现示例

**Comment by luoxiao-supermap** [comment]
https://jsfiddle.net/owhpy4vs/4/
![Uploading image.png…]()

**Comment by luoxiao-supermap** [comment]
![image](https://github.com/sakitam-fdd/ol3Echarts/assets/97505033/936b52b2-cbbf-437b-a236-a09c84e8a582)

**Comment by sakitam-fdd** [comment]
@luoxiao-supermap 好的，收到，我来看下

**Comment by sakitam-fdd** [comment]
@luoxiao-supermap 
![image](https://github.com/sakitam-fdd/ol3Echarts/assets/19517451/ab944139-c47d-4898-8515-e3b867a1c621)
似乎是这个问题导致的，奇怪的是 rollup 已经配置了，我来看下

**Comment by sakitam-fdd** [comment]
大致确认是 VERSION 的问题，ol 在生成 umd 的时候这个字段好像丢失了，在 esm 下是正常的

**Comment by sakitam-fdd** [comment]
@luoxiao-supermap 麻烦重新发一下 PR 到 master 吧，dev 分支是废弃的，顺便 rollup 的配置页改下，感谢

external
```js
module.exports = [
  'ol',
  'ol/util',
  'ol/layer',
  'ol/source',
  'ol/proj',
  'openlayers'
];

```

globals

```js
module.exports = {
  'ol': 'ol',
  'ol/util': 'ol.util',
  'ol/layer': 'ol.layer',
  'ol/source': 'ol.source',
  'ol/proj': 'ol.proj',
  'openlayers': 'ol',
};

```

**Comment by luoxiao-supermap** [comment]
已提交到master
