### ISSUE TITLE
饼状图拖动到四角时出现显示不全的问题

### ISSUE THREAD

**Issue by gisShield** [sakitam-fdd/ol3Echarts#14]
你好,在使用您开发的项目过程中发现饼状图pie.html示例中[饼状图示例](https://sakitam-fdd.github.io/ol3Echarts/examples/pie/pie.html) 将饼状图移动到四个边角会出现一个弧度的边界将饼状图切割开。如果不用你封装的hmap.js 而是直接用原生的ol 这种情况更加严重。

**Comment by sakitam-fdd** [comment]
@gisShield 我仔细测试了一下，感觉像是 `echarts` 在创建饼图的时候实际按照饼图创建了一个圆形画布。如果保留一个饼图，只能观察到一个弧边，两个的话就能发现两个。具体待我翻翻 `echarts` 源码看看 :joy:。

**Comment by gisShield** [comment]
@sakitam-fdd  好的 😊

**Comment by sakitam-fdd** [comment]
@gisShield 查看 `https://github.com/ecomfe/echarts/blob/84579c3e3adfd93287941267b66f3700fcc46af6/src/chart/pie/PieView.js#L358`。
``` javascript
var clipPath = new graphic.Sector({
            shape: {
                cx: cx,
                cy: cy,
                r0: 0,
                r: r,
                startAngle: startAngle,
                endAngle: startAngle,
                clockwise: clockwise
            }
        });
```

修改为 ：
``` javascript
var clipPath = new graphic.Sector({
            shape: {
                cx: cx,
                cy: cy,
                r0: 0,
                r: r * 2,
                startAngle: startAngle,
                endAngle: startAngle,
                clockwise: clockwise
            }
        });
```

然后执行 `node build/build.js` 重新打包`echarts` 可以解决此问题，主要问题应该是创建的扇形画布小于窗口。
