### ISSUE TITLE
Display bar chart in popup .

### ISSUE THREAD

**Issue by sharseema** [sakitam-fdd/ol3Echarts#15]
Hi,
I have district data but it is in two different formats (Json and CSV).So json file is used in OL3 and CSV file .Both files are having same attributes with same name. If user clicked on any district ,Popup chart will appear and inside popup square bar chart will display.
Is it possible to do bar chart inside popup using these library in ol3.

Thanks.

**Comment by sakitam-fdd** [comment]
@sharseema I guess the effect you want ？
![image](https://user-images.githubusercontent.com/19517451/36850029-9df0d742-1da0-11e8-8a12-27a42b69bc2b.png)

**Comment by sharseema** [comment]
Hi,
Yes exactly  this i want.
I have did one OL-3 with D3 example that is not working,only the y-axis values are not updated.If you know please check  this code [Link](https://codepen.io/seema30fresher/pen/paGdRz?editors=1010).

Can i get the example,how to implement bar chart in popup using OL-3 with Ol3Echarts.

Thanks a lot for reply.

**Comment by sakitam-fdd** [comment]
@sharseema Hi，
No need to use `ol3Echarts` just use [echarts](https://github.com/ecomfe/echarts)。
this code [Link](https://codepen.io/sakitam-fdd/pen/vdqxzR).
Your example  its not working because you did not update the data for Axis，you should clear the last popup and create new popup to create D3 chart。

**Comment by sharseema** [comment]
Hi,
Thanks a lot for help. Actually i did some styling and also trying to add close button and arrow at the bottom to div but not working, is it possible to add in it .
Thanks.

**Comment by sakitam-fdd** [comment]
@sharseema The code link was update.

**Comment by sharseema** [comment]
Thanks a lot .
