### ISSUE TITLE
在react项目中，使用本工具，出错！

### ISSUE THREAD

**Issue by ymrdf** [sakitam-fdd/ol3Echarts#2]
错误：TypeError: Cannot read property 'once' of null
错误位置：
  170 |   ],
  171 | };
  172 | 
> 173 | this.emap.map.once('postrender', function(e) {
  174 |   if (echartslayer !== undefined) {
  175 |     return;
  176 |   }

**Comment by ymrdf** [comment]
这是代码：
  componentDidMount() {
    this.emap = new HMap('map', {
      controls: {
        loading: true,
        zoomSlider: true,
        fullScreen: false,
      },
      view: {
        center: [11464017.313439976, 3934744.6720247352],
        extent: [
          -2.0037507067161843e7,
          -3.0240971958386254e7,
          2.0037507067161843e7,
          3.0240971958386205e7,
        ],
        projection: 'EPSG:102100',
        tileSize: 256,
        zoom: 5, // resolution
      },
      baseLayers: [
        {
          layerName: 'vector',
          isDefault: true,
          layerType: 'TileXYZ',
          tileGrid: {
            tileSize: 256,
            extent: [
              -2.0037507067161843e7,
              -3.0240971958386254e7,
              2.0037507067161843e7,
              3.0240971958386205e7,
            ],
            origin: [-2.0037508342787e7, 2.0037508342787e7],
            resolutions: [
              156543.03392800014,
              78271.51696399994,
              39135.75848200009,
              19567.87924099992,
              9783.93962049996,
              4891.96981024998,
              2445.98490512499,
              1222.992452562495,
              611.4962262813797,
              305.74811314055756,
              152.87405657041106,
              76.43702828507324,
              38.21851414253662,
              19.10925707126831,
              9.554628535634155,
              4.77731426794937,
              2.388657133974685,
            ],
          },
          layerUrl:
            'http://cache1.arcgisonline.cn/arcgis/rest/services/ChinaOnlineStreetPurplishBlue/MapServer/tile/{z}/{y}/{x}',
        },
      ],
    });
    const data = [
      {
        name: '菏泽',
        value: 194,
      },
    ];
    const geoCoordMap = {
      菏泽: [115.480656, 35.23375],
    };
    const convertData = function(data) {
      let res = [];
      for (let i = 0; i < data.length; i++) {
        let geoCoord = geoCoordMap[data[i].name];
        if (geoCoord) {
          res.push({
            name: data[i].name,
            value: geoCoord.concat(data[i].value),
          });
        }
      }
      return res;
    };
    const option = {
      title: {
        text: '全国主要城市空气质量',
        subtext: 'data from PM25.in',
        sublink: 'http://www.pm25.in',
        left: 'center',
        textStyle: {
          color: '#fff',
        },
      },
      tooltip: {
        trigger: 'item',
      },
      legend: {
        orient: 'vertical',
        y: 'top',
        x: 'right',
        data: ['pm2.5'],
        textStyle: {
          color: '#fff',
        },
      },
      openlayers: {},
      series: [
        {
          name: 'pm2.5',
          type: 'scatter',
          coordinateSystem: 'openlayers',
          data: convertData(data),
          symbolSize: function(val) {
            return val[2] / 10;
          },
          label: {
            normal: {
              formatter: '{b}',
              position: 'right',
              show: false,
            },
            emphasis: {
              show: true,
            },
          },
          itemStyle: {
            normal: {
              color: '#ddb926',
            },
          },
        },
        {
          name: 'Top 5',
          type: 'effectScatter',
          coordinateSystem: 'openlayers',
          data: convertData(
            data
              .sort(function(a, b) {
                return b.value - a.value;
              })
              .slice(0, 6),
          ),
          symbolSize: function(val) {
            return val[2] / 10;
          },
          showEffectOn: 'render',
          rippleEffect: {
            brushType: 'stroke',
          },
          hoverAnimation: true,
          label: {
            normal: {
              formatter: '{b}',
              position: 'right',
              show: true,
            },
          },
          itemStyle: {
            normal: {
              color: '#f4e925',
              shadowBlur: 10,
              shadowColor: '#333',
            },
          },
          zlevel: 1,
        },
      ],
    };

    this.emap.map.once('postrender', function(e) {
      if (echartslayer !== undefined) {
        return;
      }
      var echartslayer = new ol3Echarts(this.emap.map, {
        target: '.ol-overlaycontainer',
        source: '',
        destination: '',
      });
      echartslayer.chart.setOption(option);
    });
  }

**Comment by sakitam-fdd** [comment]
因为这个使用了hmap-js这个包，你看下有没有引用这个，或者你可以打印一下HMap这个变量，和this.emap

**Comment by ymrdf** [comment]
用了这个包了
等我打印完了您看一下啊！

**Comment by ymrdf** [comment]
map 属性是null

**Comment by sakitam-fdd** [comment]
```javascript
this.emap = new HMap('map', {
controls: {
loading: true,
zoomSlider: true,
fullScreen: false,
}
}
```
地图未实例化成功，这个字符串 `map` 是地图容器的 `id`, 检查一下是否准备了地图容器的dom元素。

**Comment by ymrdf** [comment]
好了！太感谢了！我原先不知道这个‘map'，代表元素，还以为是一个普通参数呢！

**Comment by ymrdf** [comment]
再请问下.ol-overlaycontainer和’map'这两个元素的关系有要求吗？

**Comment by sakitam-fdd** [comment]
你用过openlayers的话你就会知道 `.ol-overlaycontainer` 是实例化后创建的，这个dom包含在地图容器内。一同创建的还有 `.ol-overlaycontainer-stopevent`, 具体区别字面就差不多能理解，一个会阻止dom内的元素向地图传递事件，另一个不会。
