### ISSUE TITLE
当前事件触发重新setOption的机制无法支持echarts增量数据渲染。请问考虑修改支持吗？

### ISSUE THREAD

**Issue by tangqinGiser** [sakitam-fdd/ol3Echarts#20]
当前绑定的map拖动缩放等事件是直接重新setOption，但没有appendData，导致数据为空，增量渲染失败，请问考虑支持echarts增量数据渲染的功能吗？

**Comment by sakitam-fdd** [comment]
@tangqinGiser 这个问题需要想一下，增量渲染后拖动再重绘，渲染数据是appendData后的数据还是之前的数据，中间是否需要记录...

**Comment by tangqinGiser** [comment]
![image](https://user-images.githubusercontent.com/30792630/39036747-0e28e5ea-44b1-11e8-8a6e-a61d1173487f.png)

![image](https://user-images.githubusercontent.com/30792630/39036724-ff1046e8-44b0-11e8-99fa-2a1ac31fe372.png)

我试着加了一个appendData方法，页面调用echartslayer.appendData获取数据，同时存了一份，然后触发事件的时候让chart append 存起来的数据，这样可以达到效果，解决了当前的问题，但是，纠结的是，这样就维护了两套data，对运行内存可能有一些些影响。
请问你有没有更好的想法？

**Comment by tangqinGiser** [comment]
也感觉在ol3Echarts里面这么维护一套数据echarts的数据，有点，，，怪怪的。。。

**Comment by sakitam-fdd** [comment]
@tangqinGiser 确实有点不好，这个问题周末我想想，因为现在这个渲染效率实在不行:relieved:

**Comment by tangqinGiser** [comment]
您好，请问有更好的解决方案吗？
