### ISSUE TITLE
There exists something wrong when initializing and removing the object of  ol3Echarts.

### ISSUE THREAD

**Issue by Southjor** [sakitam-fdd/ol3Echarts#30]
1.在ol5版本,必须初始化地图的时候创建olEcharts对象吗?
1.调用remove方法移除对象之后,重新添加失败.

**Comment by sakitam-fdd** [comment]
@Southjor 
- ol5版本采用的是 [ol-echarts](https://www.npmjs.com/package/ol-echarts), 首页文档有提到。
- EChartsLayer 对象的初始化可以在任何时候，和ol图层相同的用法，在地图初始化完成后调用 `echartslayer.appendTo(map)`。
- `调用remove方法移除对象之后,重新添加失败`，这个问题我这边未重现，可以提供一下示例代码吗？

```javascript
this.initChart(option);
        window.setTimeout(() => {
          this.chart.remove();
          window.setTimeout(() => {
            this.initChart(option);
          }, 5000)
        }, 5000)
```

**Comment by Southjor** [comment]
这是我的初始化代码, 
   initEcharts(projection) {
        this.echartslayer = new EChartsLayer(null, {
            hideOnMoving: true,
            hideOnZooming: true,
            source: projection ? projection : 'EPSG:4326'
        });
        this.echartslayer.appendTo(this);
        // this.render();
    }

这是添加数据方法
    echartsLayer(options) {
        //获取option
        this.migrationLayer = this.getMigration(this.migration);
        this.echartslayer.setChartOptions(options ? options : this.migrationLayer);
    }

如果initEcharts写在ol地图controller里边,回添加成功,如果地图初始化之后再执行(比如用按钮执行),
则添加失败,页面有canvas,但是不显示,可能是数据没有填充上.
我是自定义了一个类 , 继承ol.Map ,方法都写在这里边,您可以试一下,看能不能复现
class BaseMap extends Map

**Comment by Southjor** [comment]
我又试了试,确实是继承ol.Map的问题,  您看这个能解决吗?

**Comment by Southjor** [comment]
额,不好意思,我找到问题了,  原因是引入ol-ceiusm,  开启三维就会出现这种情况;
原因,根据class获取ol-overlaycontainer的时候,  取到的是ol-cesium的对象元素,所以,canvas生成位置错了

**Comment by sakitam-fdd** [comment]
嗯嗯，好的，这也可以给后面使用的留一个解决方案:grinning:，没其他问题我就先关掉这个issure了。
