### ISSUE TITLE
一个页面中同时创建多个openlayer地图的时候，所有的echart地图实例都添加到最后一张地图上了

### ISSUE THREAD

**Issue by sunday60004** [sakitam-fdd/ol3Echarts#32]
我的页面中同时创建了2个openlayer地图，每个地图都添加了echarts地图对象，界面呈现的结果所有的数据都添加到了最后一张openlayer地图上，第一张地图没有添加任何数据，求解？
![image](https://user-images.githubusercontent.com/28419917/50261877-709d6e00-0449-11e9-99a5-44f529356b59.png)

**Comment by a24576946** [comment]
请问这个问题解决了吗？项目上很着急

**Comment by sakitam-fdd** [comment]
@a24576946 可能需要稍等两天，有兴趣可以处理一下 [问题定位](https://github.com/sakitam-fdd/ol3Echarts/blob/f8183acc2b7a0bc5903efe458df454ee7d3b7a23/packages/ol3-echarts/src/index.js#L210) 给我发个 pr。

**Comment by kyleinfo** [comment]
年后换服务器发现几个月前的代码全挂了，看了源代码 v1.3.6 的处理方式是有 bug 的，[getTarget](https://github.com/sakitam-fdd/ol3Echarts/blob/28cd57bc922603435ba376d8f4537a66dfd4a335/packages/canvas-render/src/helper.js#L38) 支持 id，className，TagName 和 querySelectorAll 查找 dom，但是 v1.3.6 只考虑了 className，TagName 两种情况，ol 的 getViewport() 返回的是 HTMLElement，HTMLElement 是没有 getElementById 和 querySelectorAll 方法的。
我简单处理了一下，用 getElementById 和 querySelectorAll 时指定为 docment ：
```
const getTarget = (selector, doc = document) => {
  let dom = (function () {
    let found;
    return doc && /^#([\w-]+)$/.test(selector)
      ? (found = document.getElementById(RegExp.$1)) // eslint-disable-line
        ? [found]
        : [] // eslint-disable-line
      : Array.prototype.slice.call(
        /^\.([\w-]+)$/.test(selector)
          ? doc.getElementsByClassName(RegExp.$1)
          : /^[\w-]+$/.test(selector)
            ? doc.getElementsByTagName(selector)
            : document.querySelectorAll(selector)
      );
  })();
  return dom;
};
```
我之前的处理方式是创建完 map，找到 dom 给它设置 id，getTarget 就会走 getElementById 这条途径，不至于走 getElementsByClassName 导致所有图全在一张图上。

`document.getElementById("mid_map").firstChild.children[1].id = "mid_map_id";`

**Comment by sakitam-fdd** [comment]
@kyleinfo 是的确实会有这个问题，但是现在整体的处理方式还是有点不完美，如果有更好的解决方案可以发个Pull Request。另外一个就是建议锁定一下版本，因为现在的整体测试用例没有完全覆盖，有些时候的大问题的修复对之前版本的兼容考虑的还不够 😢
