### ISSUE TITLE
comon.js not found

### ISSUE THREAD

**Issue by qiernonstop** [sakitam-fdd/ol3Echarts#37]
Hi, In Page http://sakitam-fdd.cn/ol3Echarts/static/examples/webgl/bar3d.html error:
GET http://sakitam-fdd.cn/ol3Echarts/static/assets/scripts/common.js net::ERR_ABORTED 404 (Not Found)

**Comment by sakitam-fdd** [comment]
@qiernonstop 3d柱状图是还未实现的，所以示例没有完成:relieved:
