### ISSUE TITLE
地图和图表鼠标事件冲突

### ISSUE THREAD

**Issue by hbh520** [sakitam-fdd/ol3Echarts#51]
环境：
    "ol": "^6.1.1",
    "ol-echarts": "^2.0.1",
    "echarts": "^4.5.0",

第一种情况：var echartLayer = new EChartsLayer(option,{
            source: 'EPSG:2437',
            hideOnMoving: true,
            insertFirst: true, // https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
            stopEvent: true, // https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
            polyfillEvents: false, // 代理echrats图层的 mousedown mouseup click 事件
          });
          stopEvent为ture是，echarts图标可以进行交互，但是openlayers就是去了交互，地图拖动缩放都失效
第一种情况： stopEvent为false是，情况正好相反，地图反应正常，图标无交互

**Comment by sakitam-fdd** [comment]
@hbh520 应该和 #45 问题类似，可以看下解决办法，但是目前没有完美解决方案

**Comment by hbh520** [comment]
@sakitam-fdd 我在你回答之前就按照之前的issue修改了，但是还是出现了问题，其他的问题倒是没有，就是地图无法拖动，缩放是没问题

**Comment by hbh520** [comment]
可以了，我采用集成的方式就可以了，原先直接直接设置的，谢谢啦

**Comment by sakitam-fdd** [comment]
@hbh520 @changqingom @yangdengxian @Mevius021 感谢 @kyleinfo 的PR #55，解释了一些原因和添加一部分事件的Mock，可以尝试一下新版本 v2.0.2
