### ISSUE TITLE
饼图tooltip悬浮窗没有出现

### ISSUE THREAD

**Issue by Mevius021** [sakitam-fdd/ol3Echarts#52]
"ol": "^6.1.1"
"ol-echarts": "^2.0.1"
"vue-element-admin": "4.2.1"
使用饼图的时候，悬浮窗没有出现，用console.log去调试，发现悬浮事件也没有触发
`var options = {
        tooltip : {
          show : true,
          trigger: 'item',
          formatter: function(params){
                    console.log(params)
          },
        },
        series: [],
        color: ['#0085c7','#18db94','#ff6600','#e31b14']
      };`

**Comment by sakitam-fdd** [comment]
@Mevius021 #45 #51 问题类似

**Comment by Mevius021** [comment]
> @Mevius021 #45 #51 问题类似

感谢帮助
