### ISSUE TITLE
这个示例如何实现？

### ISSUE THREAD

**Issue by mrerhuo** [sakitam-fdd/ol3Echarts#53]
https://www.echartsjs.com/examples/zh/editor.html?c=map-HK

`myChart.showLoading();

$.get(ROOT_PATH + 'data/asset/geo/HK.json', function (geoJson) {

    myChart.hideLoading();

    echarts.registerMap('HK', geoJson);

    myChart.setOption(option = {
        series: [
            {
                name: '香港18区人口密度',
                type: 'map',
                mapType: 'HK', // 自定义扩展图表类型
            }
        ]
    });
});`

**Comment by mrerhuo** [comment]
我引入了
this.echartslayer = new ol3Echarts(null, {
          hideOnMoving: true,
          hideOnZooming: true
        });
        this.echartslayer.appendTo(this.map);
this.Ajax.get("../static/map_polygon.json").then(msg => {
        echarts.registerMap("MLP", msg.data);
        var option = {
          series: [
            {
              type: "map",
              map: "MLP"
            }
          ]
        };
        this.echartslayer.setChartOptions(option);
      });
这样子简单的加载地图。就是不显示。

**Comment by sakitam-fdd** [comment]
@mrerhuo 暂时无法支持map类型的图表，可以直接使用数据加载到ol的VectorLayer上，参考一下这个：https://github.com/sakitam-fdd/ol3Echarts/blob/master/website/static/examples/map/city.html
