### ISSUE TITLE
你好是网站挂了还是你删除OL迁徙图页面了？

### ISSUE THREAD

**Issue by zxjin001** [sakitam-fdd/ol3Echarts#54]
http://sakitam-fdd.cn/ol3Echarts/#/index
这个链接没了，你做了很多 OL 风场图等很有学习借鉴意义。

**Comment by sakitam-fdd** [comment]
@zxjin001 暂时先看这个吧：https://sakitam-fdd.github.io/ol3Echarts/#/index，腾讯新网的域名不允许解析到github了，摊手.jpg
