### ISSUE TITLE
如何绘制饼图或者柱状图

### ISSUE THREAD

**Issue by dyh333** [sakitam-fdd/ol3Echarts#6]
如题，能否给个demo

**Comment by sakitam-fdd** [comment]
切到dev分支，查看 `https://github.com/sakitam-fdd/ol3Echarts/blob/dev/docs/examples/pie/pie.html`。
![image](https://user-images.githubusercontent.com/19517451/34568981-5fe3a9d6-f1a2-11e7-8223-376ae345e668.png)。
理论支持所有图表，但是现在有点问题，属于实验性功能。
