### ISSUE TITLE
hideOnZooming不生效

### ISSUE THREAD

**Issue by GarasChan** [sakitam-fdd/ol3Echarts#69]
设置hideOnZooming: true，缩放时图层未隐藏

**Comment by sakitam-fdd** [comment]
@ChenGuanglin0924 这个暂时实现不了哈，ol 没有对应 zoomstart 和 zoomend 事件，可能需要通过接管鼠标事件来实现

**Comment by ChenGuanglin0924** [comment]
@sakitam-fdd 那这参数是不是不应该体现在api里面

**Comment by sakitam-fdd** [comment]
@ChenGuanglin0924 方便的话，发个pr吧 😃

**Comment by sakitam-fdd** [comment]
在 v3.0.1 和 v4.0.1 之后实现了相关功能，请升级到此版本
