### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by yejiyang** [sakitam-fdd/ol3Echarts#70]
Hi 

I found the examples screenshot are really interesting. How I can run it locally?

Seccess on step 1 "yarn run bootstrap". 

I got this when run "yarn run dev". How I can check the pages in the web browser?

Thanks in advance. 
-----------------
```
~/dev/webgis/test/ol3Echarts:master$ yarn run dev
yarn run v1.22.5
$ lerna run dev
lerna notice cli v3.22.1
lerna info Executing command in 2 packages: "yarn run dev"
```

**Comment by sakitam-fdd** [comment]
@yejiyang 
```bash
git clone https://github.com/sakitam-fdd/ol3Echarts.git
yarn run bootstrap
yarn run dev
yarn run website
```
