### ISSUE TITLE
bug - openlayers v6.4.3 

### ISSUE THREAD

**Issue by donotlb** [sakitam-fdd/ol3Echarts#71]
## 环境

* "ol": "^6.4.3"
* "ol-echarts": "^2.0.3"
* "echarts": "^4.9.0"

## 问题

以这个 [饼图 demo](https://codesandbox.io/s/ol-echarts-example-sfzvh?file=/package.json) 为例, 如果把 ol 依赖从 6.1.1 改为 6.4.3, 则地图初始化后, 再点击地图, 出现报错: Cannot read property 'button' of undefined

如果设置 `polyfillEvents: false` 可以解决该问题, 但饼图的 hover 事件就无效了

**Comment by WBboboan** [comment]
我用的"ol": "^6.5.0"，"ol-echarts": "^2.0.3"，"echarts": "^4.9.0"。目前跟您遇到的问题一样，请问您现在解决了吗？

**Comment by donotlb** [comment]
> 我用的"ol": "^6.5.0"，"ol-echarts": "^2.0.3"，"echarts": "^4.9.0"。目前跟您遇到的问题一样，请问您现在解决了吗？

我把 ol 库降到 6.1.1 版本了

**Comment by WBboboan** [comment]
OK,那我也先降下版本

**Comment by sakitam-fdd** [comment]
@donotlb @WBboboan https://codesandbox.io/s/ol-echarts-example-sfzvh?file=/package.json 我简单测试了一下，应该可以了

**Comment by WBboboan** [comment]
> @donotlb @WBboboan https://codesandbox.io/s/ol-echarts-example-sfzvh?file=/package.json 我简单测试了一下，应该可以了

OK
