### ISSUE TITLE
使用北京地方坐标系，画lines图（航线图），看不见

### ISSUE THREAD

**Issue by kuazhangxiaoai** [sakitam-fdd/ol3Echarts#73]
使用北京地方坐标系，画lines图，看不见。标题能看见，backgroundColor也没问题，就是lines看不到，坐标大概是（40000，360000），是不是坐标值超出范围了呢？

**Comment by sakitam-fdd** [comment]
@kuazhangxiaoai 不支持地方坐标系的，需要转成wgs84
