### ISSUE TITLE
有没有可能把L7封装到ol里面呢？ 

### ISSUE THREAD

**Issue by lzp0070007** [sakitam-fdd/ol3Echarts#75]
有没有可能把L7封装到ol里面呢？ 感觉L7效果好很多

**Comment by sakitam-fdd** [comment]
@lzp0070007 这个不建议吧，L7 毕竟是 三维层面的，其实更建议使用 mapbox-gl或者deck.gl换掉 ol（如果有更专业的 gis 需求那还是 ol 可靠）
