### ISSUE TITLE
似乎不支持 series.map 类型？

### ISSUE THREAD

**Issue by dragon8github** [sakitam-fdd/ol3Echarts#77]
不支持 echarts 地图吗？毕竟 echarts 的API比较丰富，我还想盖一层呢。

![image](https://user-images.githubusercontent.com/13919724/103537053-9e3d9e80-4ece-11eb-8579-44b69e99c2fd.png)

**Comment by sakitam-fdd** [comment]
@dragon8github map 类型暂时无法支持，其实如果 gis 层面需求不重的话可以完全使用 echarts 做可视化
