### ISSUE TITLE
mapBrowserPointerEvent

### ISSUE THREAD

**Issue by znxd-wh** [sakitam-fdd/ol3Echarts#81]
用ol6.5.0版本时，鼠标悬浮在点上的时候，会报错，不出现悬浮窗体了。ol降版本到6.1.1则不会出现该问题。
原因是ol 6.5.0没有mapBrowserPointerEvent，统一改为了mapBrowserEvent。
EChartsLayer.prototype.mouseMove = function (event) {
        if (this.$chart) {
            var target = event.originalEvent.target;
            while (target) **{**
                if (target.className === 'ol-overlaycontainer-stopevent') {
                    this.$chart.getZr().painter.getViewportRoot().dispatchEvent(mockEvent('mousemove', event));
                    return;
                }
                target = target.parentElement;
            }
        }
    };
用ol6.5.0版本，这个event类型有问题。关于mouse的event都存在问题。

**Comment by sakitam-fdd** [comment]
@znxd-wh https://codesandbox.io/s/ol-echarts-example-sfzvh?file=/src/index.js 我记得应该是 OK 的，你再确认下，如果还有问题请重新打开并给一个codesandbox最小可复现的示例
