### ISSUE TITLE
Cannot set property 'disposed' of null

### ISSUE THREAD

**Issue by nicetyler** [sakitam-fdd/ol3Echarts#87]
安装之后报这个错误，我是想用openlayers6集成echarts进去

**Comment by sakitam-fdd** [comment]
@nicetyler 要不先锁定 ol 版本 "ol": "6.5.0"，之后的版本没有试过，不太清楚最新的 ol 核心修改了什么

**Comment by nicetyler** [comment]
@sakitam-fdd 我这边弄好了，好像是吧echarts降到4.9版本，然后我没全局里面引入就没报错了
