### ISSUE TITLE
Uncaught TypeError: EChartsLayer__default.default is not a constructor

### ISSUE THREAD

**Issue by guzicheng90** [sakitam-fdd/ol3Echarts#88]
您好，使用过程中遇到两个问题：
1、我想把功能封装成接口使用，用 ```import EChartsLayer from 'ol-echarts';``` 方式引入，再用rollup打包，外部调用时出现```Uncaught TypeError: EChartsLayer__default.default is not a constructor``` 报错
请问是什么问题？
2、另请指教：setMap方法中，为何需要判断```map instanceof ol.Map``` ？调用我自己封装的库（npm引的ol），cdn方式引的ol-echarts，这边map对象判断会一直过不去？
谢谢

**Comment by sakitam-fdd** [comment]
@guzicheng90

**Comment by guzicheng90** [comment]
谢谢回复 第一个问题确实是echarts版本有关
